spring.application.name=backend
spring.threads.virtual.enabled=true

# Logging levels
logging.level.org.springframework.cloud.gcp=DEBUG
logging.level.com.google.cloud.spring.data.firestore=DEBUG
logging.level.com.google.cloud.firestore=TRACE

# Custom App logic
app.seeding.enabled=false

# Standardize on these keys for both Spring Cloud and your custom Config
google.cloud.project-id=cartshare-484109
google.cloud.key-path=/Users/miguelloureiro/repos/keys/google-key-vps.json

# If you use Spring Cloud GCP libraries elsewhere, link them to the same values
spring.cloud.gcp.firestore.project-id=${google.cloud.project-id}
spring.cloud.gcp.credentials.location=file:${google.cloud.key-path}