package com.cartshare.backend.core.model;

import com.google.cloud.firestore.annotation.DocumentId;
import com.google.cloud.spring.data.firestore.Document;
import lombok.NonNull;

import java.util.List;

/**
 * Product entity representing items in the Firestore "products" collection.
 *
 * Fields:
 * - id: Auto-generated by Firestore (document ID), optional during creation
 * - productName: Name of the product
 * - categoryId: Reference to a category (required)
 * - isOfficial: true = from Excel seed, false = user-contributed
 * - searchKeywords: Auto-generated keywords for autocomplete (both accented and normalized forms)
 *
 * Examples:
 * - Official product: new Product(null, "Arroz", "alimentos", true, ["arroz"])
 * - User product: new Product(null, "iPhone 15", "electronics", false, ["iphone", "15"])
 */
@Document(collectionName = "products")
public record Product(
        @DocumentId String id,
        String productName,
        @NonNull String categoryId,
        boolean isOfficial,              // true = Excel seed, false = User-contributed
        List<String> searchKeywords      // Auto-generated, both accented and normalized forms
) {
    /**
     * Compact constructor for validation (optional but recommended)
     */
    public Product {
        if (productName != null && productName.isBlank()) {
            throw new IllegalArgumentException("Product name cannot be blank");
        }
        if (categoryId == null || categoryId.isBlank()) {
            throw new IllegalArgumentException("Category ID is required and cannot be blank");
        }
        if (searchKeywords == null) {
            searchKeywords = List.of();
        }
    }

    /**
     * Create a new Product without ID (for new documents)
     * Used when creating products from user input or initial seed
     */
    public static Product create(String productName, String categoryId, boolean isOfficial, List<String> searchKeywords) {
        return new Product(null, productName, categoryId, isOfficial, searchKeywords);
    }

    /**
     * Create a new Product with all fields
     * Used when loading from Firestore or testing
     */
    public static Product of(String id, String productName, String categoryId, boolean isOfficial, List<String> searchKeywords) {
        return new Product(id, productName, categoryId, isOfficial, searchKeywords);
    }

    /**
     * Create an official product (from Excel seed)
     */
    public static Product createOfficial(String productName, String categoryId, List<String> searchKeywords) {
        return new Product(null, productName, categoryId, true, searchKeywords);
    }

    /**
     * Create a user-contributed product
     */
    public static Product createUserContributed(String productName, String categoryId, List<String> searchKeywords) {
        return new Product(null, productName, categoryId, false, searchKeywords);
    }
}